/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../STM32F103_DRIVERS/inc/STM32F103_SPI_DRIVER.h"
#include "../STM32F103_DRIVERS/inc/STM32_F103X6.h"
#include "../STM32F103_DRIVERS/inc/STM32_F103C6_RCC_DRIVER.h"
#include "../STM32F103_DRIVERS/inc/STM32_F103C6_GPIO_Driver.h"
#include "../STM32F103_DRIVERS/inc/STM32_F103C6_EXTI_DRIVER.h"
#include "../STM32F103_DRIVERS/inc/STM32_F103F6_USART_DRIVER.h"

#define SPI_ACT_MASTER
//#define SPI_ACT_SLAVE


void clock_Init(void)
{
	//Enable Clock FOR GPIOA
	RCC_GPIOA_CLK_EN();
	//Enable Clock FOR GPIOB
	RCC_GPIOB_CLK_EN();

	//Enable AFIO Clock
	RCC_AFIO_CLK_EN();
}

uint16_t ch;

void SPI_irq_callback(IRQ_SPI_src_t irq_src){
#ifdef SPI_ACT_SLAVE
	if(irq_src.RXNE){
		ch = 0xf;
		MCAL_SPI_TX_RX(SPI1, &ch, pollingDisable);
		MCAL_USART_send_data(USART1, &ch, enable);
	}
#endif
}

void UART_callback(void){
#ifdef SPI_ACT_MASTER
	MCAL_USART_recive_data(USART1, &ch, disable);
	MCAL_USART_send_data(USART1, &ch, enable);

	//Send to SPI

	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 0);
	MCAL_SPI_TX_RX(SPI1, &ch, pollingEnable);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);
#endif

}

int main(void)
{
	clock_Init();
	USART_config_t config;

	config.baud_rate = USART_BAUD_RATE_115200;
	config.hwFlCt = USART_HWFLCT_NONE;
	config.IRQ_enable = USART_IRQ_ENABLE_NONE;
	config.p_IRQ_callback = NULL;
	config.parity = USART_PARITY_NONE;
	config.data_lenght = USART_DATA_LENGHT_8B;
	config.stop_bits = USART_STOP_BITS_1;
	config.USART_mode = USART_MODE_TX_RX;

	MCAL_USART_init(USART1, &config);
	MCAL_USART_set_pins(USART1);

	//==================SPI INIT====================
	//PA4 >> SPI1_NSS
	//PA5 >> SPI1_SCK
	//PA6 >> SPI1_MISO
	//PA7 >> SPI1_MOSI
	SPI_config_t config1;
	GPIO_PIN_Config_t pinConfig;

	//Common configuration between master & slave
	config1.CLK_phase = 	SPI_CLK_PHASE_EDGE2_DATA_CAPTURE;
	config1.CLK_polarity = SPI_CLK_POLARITY_IDLE_HIGH;
	config1.data_size = SPI_DATA_SIZE_8BIT;
	config1.frame_format = SPI_FRAME_FORMAT_MSB;
	//Assume by default pclk2 = 8MHZ
	config1.baud_rate_prescaler = SPI_BAUD_RATE_PRESCALER_8;
	config1.communication_mode = SPI_DIRECTION_2LINES;

#ifdef SPI_ACT_MASTER
	config1.device_mode = SPI_DEVICE_MODE_MASTER;
	config1.IRQ_enable = SPI_IRQ_ENABLE_NONE;
	config1.p_IRQ_callback = NULL;
	config1.NSS = SPI_NSS_SW_NSS_INTERNAL_SOFT_SET;

	//Configuring SS by GPIO pin 4
	pinConfig.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	pinConfig.GPIO_PinNumber = GPIO_PIN_4;
	pinConfig.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA, &pinConfig);

#endif

#ifdef SPI_ACT_SLAVE
	config1.device_mode = SPI_DEVICE_MODE_SLAVE;
	config1.IRQ_enable = SPI_IRQ_ENABLE_RXNEIE;
	config1.NSS = SPI_NSS_HW_SLAVE;
	config1.p_IRQ_callback = SPI_irq_callback;


#endif

	MCAL_SPI_init(SPI1, &config1);
	MCAL_SPI_set_pins(SPI1);


	while(1)
	{
	}

}
