/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../HAL/inc/KEYPAD.h"
#include "../HAL/inc/LCD.h"

#define ZERO  0x01
#define ONE   0x79
#define TWO   0x24
#define THREE  0x30
#define FOUR  0x4C
#define FIVE  0x12
#define SIX   0x02
#define SEVEN 0x19
#define EIGHT 0x00
#define NINE  0x10




void Clock_init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}


void GPIO_init()
{
	GPIO_PIN_Config_t PinCfg;

	//9->15 are for seven segment
	PinCfg.GPIO_PinNumber = GPIO_PIN_9;
	PinCfg.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_10;
	PinCfg.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_11;
	PinCfg.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_12;
	PinCfg.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);


	PinCfg.GPIO_PinNumber = GPIO_PIN_14;
	PinCfg.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	PinCfg.GPIO_PinNumber = GPIO_PIN_15;
	PinCfg.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_SPEED = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

}



int main(void)
{
	Clock_init();
	GPIO_init();
	LCD_INIT();

	unsigned char key_pressed;
	LCD_WRITE_STRING("HEY");
	delay_ms(30);
	LCD_clearscreen();

	unsigned char LCD_DISPLAY [11] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0'};
	unsigned char DISPLAY [11] = {ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO};
	for (unsigned char i = 0; i < 11; i++) {
		LCD_WRITE_CHAR(LCD_DISPLAY[i]);
		MCAL_GPIO_WritePort(GPIOB, DISPLAY[i] << 9);
		delay_ms(100);

	}

	LCD_clearscreen();
	KEYPAD_INIT();
	LCD_WRITE_STRING("Keypad is ready");
	delay_ms(30);
	LCD_clearscreen();

	while (1) {

		key_pressed = KEYPAD_GETCHAR();
		switch (key_pressed) {
		case '~':
			break;
		case '?':
			LCD_clearscreen();
			break;
		default:
			//				if (key_pressed >= '0' && key_pressed <= '9') {
			//				        LCD_WRITE_CHAR(key_pressed);
			//				        MCAL_GPIO_WritePort(GPIOB, DISPLAY[key_pressed - '0'] << 9);
			//				    } else {
			//				        LCD_WRITE_CHAR(key_pressed);
			//				    }
			//				    break;
			//
			//
			//			}
			LCD_WRITE_CHAR(key_pressed);
			break;
		}

	}
}
