/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "MemMap.h"
void clock_init(){

	// enable clock for AFIO
	RCC_APB2ENR |= (1<<0);
	// enable clock for GPIOA
	RCC_APB2ENR |= (1<<2);

}




void GPIO_INIT(){

	//configure PA0 as input floating
	GPIOA_CRL &= ~(0b11<<0);
	GPIOA_CRL |=(0b01<<2);
	//configure PA13 as output
	GPIOA_CRH |= (0b01<<20);
	GPIOA_CRH &= ~(0b11<<22);



}

void EXTI0_IRQHANDLER(){

	//toggle led
	GPIOA_ODR ^= (1<<13);
	//clear pending interrupt
	EXTI_PR |=  (1<<0);


}

void EXTI_init(){

	// configure PORTA0 as interrupt line0
	AFIO_EXTICR1 = 0;
	// RISING EDGE
	EXTI_PTSR |= (1<<0);
	// ENABLE interrupt mask register
	EXTI_IMR |= (1<<0);
	// enable NVIC
	NVIC_ISER0 |= (1<<6);
}


int main(void)
{

	clock_init();
	GPIO_INIT();
	EXTI_init();

	while(1);



}
