/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "../STM32F103_DRIVERS/inc/STM32_F103X6.h"
#include "../STM32F103_DRIVERS/inc/STM32_F103C6_EXTI_DRIVER.h"
#include "../STM32F103_DRIVERS/inc/STM32_F103C6_GPIO_Driver.h"
#include "../STM32F103_DRIVERS/inc/STM32_F103F6_USART_DRIVER.h"
#include "../HAL/inc/KEYPAD.h"
#include "../HAL/inc/LCD.h"

uint16_t ch;

//APIs
void clock_init(void);

void ALI_UART_IRQ_Callback(void){
	MCAL_USART_recive_data(USART1, &ch,disable);
	MCAL_USART_send_data(USART1, &ch, enable);
}

int main(void){

	//Initializing Peripherals
	clock_init();
	USART_config_t config;

	config.baud_rate = USART_BAUD_RATE_115200;
	config.hwFlCt = USART_HWFLCT_NONE;
	config.IRQ_enable = USART_IRQ_ENABLE_RXNEIE;
	config.p_IRQ_callback = ALI_UART_IRQ_Callback;
	config.parity = USART_PARITY_NONE;
	config.data_lenght = USART_DATA_LENGHT_8B;
	config.stop_bits = USART_STOP_BITS_1;
	config.USART_mode = USART_MODE_TX_RX;

	MCAL_USART_init(USART1, &config);
	MCAL_USART_set_pins(USART1);

	while(1){

		/*
		//polling
		MCAL_USART_recive_data(USART1, &ch, enable);
		MCAL_USART_send_data(USART1, &ch, enable);
		 */
	}
}


void clock_init(void){
	RCC_GPIOA_CLK_EN();

	RCC_GPIOB_CLK_EN();

	RCC_AFIO_CLK_EN();

}
